---
title: "Untitled"
author: "RN7"
date: "10/8/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



# Introduction

matchday summary graphics



2nd season so build MORE for more context 




# Target Audience

# Design Choices

- sparkline timeline: no, cum xg covers that and can't see plot point easily in graph. also the nature of the chronological setup already means you get that aspect of the game anyways
better to focus on something that's easier to see at first glance as highlights the main idea of the table >> shost. 

# Data

Data source: understat.com




# Code Breakdown

## Creating the soccer field plots






## Combining plots to data frame


shot points could be color of team. rather keep consistently black as some colors might not work so well as solid points >>> use black as the stroke outline?

## Actual table




Image files need to be placed in output folder

## Save online to RPubs





# Acknowledgements


# Conclusion & Future Steps







